




import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Album': 'My Album',
          'Q&A':'Q&A',
          'Booking Register':'Booking Register',
          'Enquiry':'Enquiry',
          'Promos & Ads':'Promos & Ads',
          'Due Register':'Due Register',
          'Completed Events':'Completed Events',
          'UpComing Events':'UpComing Events',
          'Images':'Images',
          'Videos':'Videos',
          'My Booking':'My Booking',
          'Questions':'Questions',
          'Add Booking':'Add Booking',
          'Social Accounts':'Social Account',
          'Subscription Plan':'Subscription Plan',
          'GET STARTED':'GET STARTED',
          'Create Promos & Ads':'Create Promos & Ads',
          'ADD SERVICE':'ADD SERVICE',
          'Add Service':'Add Service',
          'ADD PAYMENT':'ADD PAYMENT',
          'Add Payment':'Add Payment',
          'Max. 10 images can be uploaded':'Max. 10 images can be uploaded',
          'No Data Available':'No Data Available',
          'Set As Profile':'Set As Profile',
          'Profile':'Profile',
          'Share':'Share'
          ,'Are You Sure':'Are You Sure',
          'Do you really want to delete this image? The same cannot be undo':'Do you really want to delete this image? The same cannot be undo',
          'Image Deleted':'Image Deleted',
          'Delete':'Delete',
          'Cancel':'Cancel',
          'Max. 2 Clips can be uploaded Upto 2 MB':'Max. 2 Clips can be uploaded Upto 2 MB',
          'Do you really want to delete this Video? The same cannot be undo':'Do you really want to delete this Video? The same cannot be undo'
          ,'Video Deleted':'Video Deleted',
          'Video Upload Done':'Video Upload Done',
          'Not select Video size more than 2 MB':'Not select Video size more than 2 MB',
          'Storage Full on this Section':'Storage Full on this Section',
          'Submit':'Submit',
          'SUBMIT':'SUBMIT',
          'Select one Option':'Select one Option',
          'field Empty':'field Empty',
          'select option':'select option',
         'pleace select services':'pleace select services',
         'Quantity':'Quantity',
         'price':'price',
         'Total':'Total',
         'remark':'remark',
         'Remark':'Remark',
         'Amount':'Amount',
         'SAVE':'SAVE',
         'Save':'Save',
         'Name':'Name',
         'Please enter your Mobile Number':'Please enter your Mobile Number',
         'Please enter your name':'Please enter your name',
         'Mobile Number':'Mobile Number',
         'Optional Mobile Number':'Optional Mobile Number',
         'Event Category':"Event Category",
         'Please select Event Category':'Please select Event Category',
         'Please select Event Start Date':'Please select Event Start Date',
         'Event Start Date':'Event Start Date',
         'Please select Event Start Date then Select End date':'Please select Event Start Date then Select End date',
         'Please select Event End Date':'Please select Event End Date',
         'Event End Date':'Event End Date',
         'Please select Event Start Time':'Please select Event Start Time',
         'Event Start Time':'Event Start Time',
         'please select Start Time':'please select Start Time',
         'please select Start Date & End Date':'please select Start Date & End Date',
         'Please select Event End Time':'Please select Event End Time',
         'Event End Time':'Event End Time',
         'Please enter your Event Address':'Please enter your Event Address',
         'Event Address':'Event Address',
         'Please Tap this field and get location':'Please Tap this field and get location',
         'Set Your Bussiness Location':'Set Your Bussiness Location',
         'CONFIRM BOOKING':'CONFIRM BOOKING',
         'Enter Quantity':'Enter Quantity',
         'Invalid Amount':'Invalid Amount',
         'Enter the Amount':'Enter the Amount',
         'Business Name':'Business Name',
         'SELECT BACKGROUND IMAGE':'SELECT BACKGROUND IMAGE',
         'Discount(%)':'Discount(%)',
         'white':'white',
         'black':'black',
         'GENERATE AD':'GENERATE AD',
         'Somthing Went Wrong':'Somthing Went Wrong',
         'UPLOAD AD':'UPLOAD AD',
         'Account Document':'Account Document',
         'Basic Information':'Basic Information',
         'Registration Information':'Registration Information',
         'Bank Information':'Bank Information',
         'MMDD Orders':'MMDD Orders',
         'My Services':'My Services',
         'Discount':'Discount',
         'Our Services':'Our Services',
         'Review':'Review',
         'Phone Diary':'Phone Diary',
         'Refer and Earn':'Refer and Earn',
         'Contact Us':'Contact Us',
         'Log Out':'Log Out'
         
        },
        'hi_IN': {
         'Log Out':'लॉग आउट',
         'Contact Us':'हमसे संपर्क करें',
         'Refer and Earn':'देखें और कमाएँ',
          'Phone Diary':'फ़ोन डायरी',
          'Review':'समीक्षा',
         'My Terms & Conditions':'मेरे नियम एवं शर्तें',
         'Our Services':'हमारी सेवाएँ',
         'Discount':'छूट',
          'My Services':'मेरी सेवाएँ',
         'MMDD Orders':'एमएमडीडी आदेश',
         'Bank Information':'बैंक संबंधी जानकारी',
         'Registration Information':'पंजीकरण सूचना',
          'Basic Information':'मूल जानकारी',
         'Account Document':'खाता दस्तावेज़',
          'Profile':'प्रोफ़ाइल',
          'UPLOAD AD':'विज्ञापन अपलोड करें',
          'Somthing Went Wrong': 'कुछ ग़लत हुआ',
          'GENERATE AD':'विज्ञापन बनाएं',
          'black':'काला',
          'white':'सफ़ेद',
          'Discount(%)':'छूट',
          'SELECT BACKGROUND IMAGE':'पृष्ठभूमि छवि चुनें',
          'Business Name':'व्यवसाय का नाम',
          'Album': 'मेरे एल्बम',
          'Q&A':'प्रश्नोत्तर',
          'Booking Register':'बुकिंग रजिस्टर',
          'Enquiry':'जाँच करना',
          'Promos & Ads':'प्रोमो और विज्ञापन',
          'Due Register':'देय रजिस्टर',
          'Completed Events':'पूर्ण हो चुके कार्यक्रम',
          'UpComing Events':'आगामी कार्यक्रम',
          'Images':'छवियां',
          'Videos':'वीडियो',
          'My Booking':'मेरी बुकिंग',
          'Questions':'प्रश्न',
          'Add Booking':'बुकिंग जोड़ें',
          'Social Accounts':'सामाजिक खाता',
          'Subscription Plan':'सदस्यता योजना',
          'GET STARTED':'शुरू करें',
          'Create Promos & Ads':'प्रोमो और विज्ञापन बनाएं',
          'ADD SERVICE':'सेवा जोड़ें',
          'Add Service':'सेवा जोड़ें',
          'ADD PAYMENT':'भुगतान जोड़ें',
          'Add Payment':'भुगतान जोड़ें',
          'Max. 10 images can be uploaded':'अधिकतम 10 छवियाँ अपलोड की जा सकती हैं',
          'No Data Available':'कोई डेटा मौजूद नहीं',
          'Set As Profile':'प्रोफ़ाइल सेट करें',
         'Share':'शेयर',
         'Are You Sure':'क्या आपको यकीन है',
         'Do you really went to delete these Item? This process cannot be undo':'क्या आप सचमुच ये आइटम हटाने गए थे? इस प्रक्रिया को पूर्ववत नहीं किया जा सकता',
         'Image Deleted':'छवि हटा दी गई',
         'Delete':'मिटाना',
         'Cancel':'रद्द करना',
         'Do you really want to delete this image? The same cannot be undo':'क्या आप सचमुच इस छवि को हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता',
         'Max. 2 Clips can be uploaded Upto 2 MB':'अधिकतम 2 क्लिप्स 2 एमबी तक अपलोड की जा सकती हैं',
         'Do you really want to delete this Video? The same cannot be undo':'क्या आप सचमुच इस वीडियो को हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता',
         'Video Deleted':'वीडियो हटा दिया गया',
         'Video Upload Done':'वीडियो अपलोड हो गया',
         'Not select Video size more than 2 MB':'2 MB से अधिक वीडियो आकार का चयन न करें',
         'Storage Full on this Section':'इस अनुभाग पर संग्रहण पूर्ण',
         'Submit':'जमा करना',
         'SUBMIT':'जमा करना',
         'Select one Option':'एक विकल्प चुनें',
         'field Empty':'फ़ील्ड ख़ाली',
         'select option':'विकल्प चुनें',
         'pleace select services':'कृपया सेवाओं का चयन करें',
         'Quantity':'मात्रा',
         'price':'कीमत',
         'Total':'कुल',
         'remark':'टिप्पणी',
         'Remark':'टिप्पणी',
         'Amount':'कीमत',
         'SAVE':'सहेजें',
         'Save':'सहेजें',
         'Please enter your name':'कृपया अपना नाम दर्ज करें',
         'Name':'नाम',
         'Please enter your Mobile Number':'अपना मोबाइल नंबर दर्ज करें',
         'Mobile Number':'मोबाइल नंबर',
         'Optional Mobile Number':'वैकल्पिक मोबाइल नंबर',
         'Event Category':'इवेंट श्रेणी',
         'Please select Event Category':'कृपया इवेंट श्रेणी चुनें',
         'Please select Event Start Date':'कृपया इवेंट आरंभ तिथि चुनें',
         'Event Start Date':'कार्यक्रम प्रारंभ दिनांक',
         'Please select Event Start Date then Select End date':'कृपया ईवेंट आरंभ तिथि चुनें',
         'Please select Event End Date':'कृपया ईवेंट समाप्ति तिथि चुनें',
         'Event End Date':'इवेंट समाप्ति तिथि',
         'Please select Event Start Time':'कृपया इवेंट प्रारंभ समय चुनें',
         'Event Start Time':'इवेंट प्रारंभ समय',
         'please select Start Date & End Date':'आरंभ तिथि और समाप्ति तिथि चुनें',
         'please select Start Time':'कृपया प्रारंभ समय चुनें',
         'Please select Event End Time':'कृपया ईवेंट समाप्ति समय चुनें',
         'Event End Time':'इवेंट समाप्ति समय',
         'Please enter your Event Address':'कृपया अपना इवेंट पता दर्ज करें',
         'Event Address':'इवेंट का पता',
         'Address':'पता',
         'Please Tap this field and get location':'कृपया इस फ़ील्ड पर टैप करें और स्थान प्राप्त करें',
         'Set Your Bussiness Location':'अपना व्यवसाय स्थान निर्धारित करें',
         'CONFIRM BOOKING':'बुकिंग की पुष्टि करें',
         'Enter Quantity':'मात्रा दर्ज करें',
         'Invalid Amount':'अमान्य राशि',
         'Enter the Amount':'राशि दर्ज करें'
        //  'Storage Full on this Section':'इस अनुभाग पर संग्रहण पूर्ण',

        },
      };
}