name: mddmerchant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.0
  flutter_spinkit: ^5.2.1
#  flutter_gifimage: ^2.0.0

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.2
  shared_preferences: ^2.3.3
  get: ^4.6.6
  flutter_localization: ^0.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  path_provider: ^2.1.5
  open_filex: ^4.6.0
  share_plus: ^10.1.3
  file_picker: ^8.1.6
  another_carousel_pro: ^1.0.2
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  pdf: ^3.11.1
  syncfusion_flutter_pdfviewer: ^28.1.36
  another_flushbar: ^1.12.30
  webview_flutter: ^4.10.0
  icons_launcher: ^3.0.0
  google_maps_flutter: ^2.10.0
  payu_checkoutpro_flutter: ^1.2.5
  crypto: ^3.0.6
  # google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  carousel_slider: ^4.2.0
  flutter_lints: ^4.0.0
  # flutter_launcher_icons: "^0.14.1"
  # font_awesome_flutter: '>= 4.7.0'
#  carousel_slider: ^4.2.0
icons_launcher:
  image_path: "assets/logo/app logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
#  flutter_icons:
#    android: true
#    ios: true
#    image_path: "assets/logo/"

flutter:
  uses-material-design: true
  assets:
#    - assets/images/
    - assets/images/main/
    - assets/images/myalbum/
    - assets/images/register/
    - assets/logo/

  fonts:
    - family: Fontmain
      fonts:
        - asset: assets/fonts/Aclonica/Aclonica-Regular.ttf
          weight: 400

    - family: sub-tittle
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 100
    - family: hindi-font
      fonts:
        - asset: assets/fonts/hindi font/NotoSerifDevanagari-VariableFont_wdth,wght.ttf
          weight: 100
#
#    - family: CustomIcons
#      fonts:
#        - asset: assets/icons/custom_icons.ttf
#    - family: list-sub
#      fonts:
#        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
#          weight: 200
#      - asset: assets/font/Caveat-Bold.ttf
#        weight: 700

#       - assets: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#     font:
#       - assets: font/Caveat/.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
